package.json

uncommented precommit in pkg json

---

package-lock.json

packageLock fix

---

server/api/apiProtection/isAdmin.js
server/api/apiProtection/isAuthenticated.js
server/api/race.js
server/api/users.js
server/api/users.spec.js
server/db/models/index.js
server/db/models/race.js
server/db/models/user.js
server/db/models/userFriend.js
server/db/models/userRace.js

early models and routes

---

oldSeed.js
script/seed.js

merge seed to master

---

server/api/userRaces.js
server/db/models/userRace.js

userRace isOwner, query routes added

---

server/api/users.js

Add createdAt attribute to get users route

---

script/seed.js
server/api/userRaces.js
server/db/models/userRace.js

seed file and userRace route updates

---

server/api/userRaces.js

percentage changed to percent userRace

---

script/seed.js

seed changed

---

server/api/index.js
server/api/userFriends.js

Adding userFriends routes

---

server/api/users.js

Minor change on users api routes

---

script/seed.js
server/api/userFriends.js
server/db/models/race.js

new seed and some routes

---

server/api/userRaces.js

new query added to get req on userRace

---

server/api/userRaces.js

fixed put req in userRaces

---

server/api/userRaces.js

fixed userRace post to return obj

---

server/api/userRaces.js

fixed loading hasStarted info in route

---

script/seed.js
server/db/models/race.js

changed seed and race models for int race lengths

---

server/api/userRaces.js

Eagerload horse

---

server/api/userRaces.js

forgot to import horse model

---

server/api/horses.js
server/api/index.js

horse routes

---

script/seed.js

seed change to make races into minutes

---

script/seed.js

gave horses imgur links

---

server/api/users.js

testhorseroute
